# Generated by Django 5.2.8 on 2025-11-26 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('service', 'Service'), ('food', 'Food & Beverage'), ('health', 'Health & Beauty'), ('tech', 'Technology'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('target_audience', models.JSONField(default=dict)),
                ('location', models.CharField(max_length=255)),
                ('contact_info', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentGenerationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekly_plan', models.JSONField(default=dict)),
                ('messaging_tone', models.CharField(max_length=100)),
                ('target_platforms', models.JSONField(default=list)),
                ('daily_actions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('social_post', 'Social Media Post'), ('product_desc', 'Product Description'), ('ad_copy', 'Ad Copy'), ('video_script', 'Video Script'), ('email', 'Email Campaign'), ('whatsapp', 'WhatsApp Message')], max_length=50)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('content_text', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_posted', models.BooleanField(default=False)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
