# Generated by Django 5.2.8 on 2025-11-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contentgenerationrequest',
            index=models.Index(fields=['ip_address', 'session_key'], name='api_content_ip_addr_84dbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgenerationrequest',
            index=models.Index(fields=['created_at'], name='api_content_created_540af5_idx'),
        ),
        migrations.AddField(
            model_name='growthplan',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_plans', to='api.businessprofile'),
        ),
        migrations.AddField(
            model_name='marketingcontent',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_content', to='api.businessprofile'),
        ),
    ]
